Hot Fixes
NUS-ALSET/games pull request #31
Opened 2018-10-29 12:28 UTC by walkwel

- Add Material-UI Library for design consistancy
- Code refactor

2018-10-30 06:24 UTC, FeynmanDNA requested changes

2018-10-30 06:24 UTC, FeynmanDNA commented on src/passengerPickup/src/simulation/tournament.js
> +      // eslint-disable-next-line
do we need to disable eslint here?

2018-10-30 06:24 UTC, FeynmanDNA commented on src/passengerPickup/src/simulation/tournament.js
> +    () => {
this code needs better indentation

2018-10-30 06:24 UTC, FeynmanDNA commented on src/passengerPickup/src/simulation/tournament.js
> +            >RESIMULATE
start a new line for the text of the button

2018-10-30 06:24 UTC, FeynmanDNA commented on src/passengerPickup/src/simulation/tournament.js
> +              <button className="btn-smaller control-btn" onClick={(e) => {
format the button to multiple lines

2018-10-30 06:24 UTC, FeynmanDNA commented on src/passengerPickup/src/simulation/tournament.js
> +        {!Store.showGameSimulation ? <div style={{ background: 'white' }}>
please start a new line for div

2018-10-30 06:24 UTC, FeynmanDNA commented on src/passengerPickup/src/simulation/tournament.js
> +        </div> : <Fragment>
split the conditionals into two lines

2018-10-30 06:24 UTC, FeynmanDNA commented on src/passengerPickup/src/simulation/tournament.js
> +              >X
new line for x

2018-10-30 06:24 UTC, FeynmanDNA commented on src/passengerPickup/src/view/ScoreDisplay.js
> +import Button from '@material-ui/core/Button'
add a ;

2018-10-30 06:24 UTC, FeynmanDNA commented on src/passengerPickup/src/view/ScoreDisplay.js
> +        onClick={() => restartGame()}> {initGame ? 'Start Game' : 'Restart'}
new line for button content

2018-10-30 06:24 UTC, FeynmanDNA commented on src/passengerPickup/src/view/ScoreDisplay.js
> +          onClick={() => pauseResumeGame()}>{store.mode === 'play' ? 'Pause' : 'Resume'}
new line for button content

2018-10-30 06:24 UTC, FeynmanDNA commented on src/passengerPickup/src/view/updater.js
> +    return (<Fragment>
please format the return

2018-10-30 10:56 UTC, walkwel commented on src/passengerPickup/src/simulation/tournament.js
> +      // eslint-disable-next-line
It was there in the code previously.

2018-10-30 11:07 UTC, walkwel commented
Code formatting changes have been corrected.

2018-11-01 01:21 UTC, FeynmanDNA commented on src/passengerPickup/package.json
> +    "@material-ui/core": "^3.0.1",
can update to 3.3.2 first.

2018-11-01 01:25 UTC, FeynmanDNA requested changes

2018-11-01 01:25 UTC, FeynmanDNA commented on src/squadGame/src/simulation/table-result.js
> +    let r = 0;
Please have more informative variable namings, instead of just `r` `a` `b`

2018-11-01 01:25 UTC, FeynmanDNA commented on src/passengerPickup/src/simulation/tournament.js
> +    () => {
@walkwel why do we have functions inside `setState`?

2018-11-01 03:52 UTC, walkwel commented on src/passengerPickup/src/simulation/tournament.js
> +    () => {
It is recommended to use a function inside Setstate instead of Object

2018-11-01 05:43 UTC, FeynmanDNA requested changes

2018-11-01 05:43 UTC, FeynmanDNA commented on src/squadGame/src/simulation/table-result.js
> +					break;
can we have the code in 2-space indentation in this file

2018-11-01 05:43 UTC, FeynmanDNA commented on src/squadGame/src/simulation/table-result.js
> +												data-bot2={item.name}
indentation issue

2018-11-01 05:43 UTC, FeynmanDNA commented on src/passengerPickup/src/simulation/tournament.js
> +            />
move this left two space

2018-11-01 05:46 UTC, FeynmanDNA requested changes

2018-11-01 05:46 UTC, FeynmanDNA commented on src/passengerPickup/src/simulation/tournament.js
> +          (<div style={{ background: 'white' }}>
need clearer indentation for this conditional block

2018-11-01 05:46 UTC, FeynmanDNA commented on src/passengerPickup/src/simulation/tournament.js
> +            }
indent left

2018-11-02 05:01 UTC, FeynmanDNA approved these changes

2018-11-02 05:01 UTC, merged